highlighter: rouge
markdown: kramdown

permalink: /:title.html
paginate: 5
plugins: [jekyll-paginate]
safe: true

# Information
title: Mohamed | Software Engineer
name: Mohamed Moanis
author: Mohamed Moanis
description: Homepage

google_analytics: UA-118569685-1

url: https://mmoanis.github.io
baseurl: /
github: mmoanis
linkedin: mmoanis
stackoverflow: users/5504460/mohamed-moanis
skype: mohamed-moanis
steam: mmoanis
avatar: mmoanis.png

#exclude: [vendor]
