highlighter: rouge
markdown: kramdown

permalink: /:title.html
paginate: 5
plugins: [jekyll-paginate]
safe: true

# Information
title:
name: Mohamed
author: Mohamed
description: Homepage

google_analytics: G-E8DE7HFHZM

url: https://mmoanis.github.io
baseurl: /
github: mmoanis
linkedin: mmoanis
stackoverflow: users/5504460/mohamed-moanis
skype: mohamed-moanis
steam: mmoanis
avatar: mmoanis.png

#exclude: [vendor]
