highlighter: rouge
markdown: kramdown

permalink: /:title.html
paginate: 5
plugins: [jekyll-paginate]
safe: true

# Information
title: Mohamed Moanis Ali | Software Engineer
name: Mohamed Moanis Ali
author: Mohamed Moanis Ali
description: Homepage

google_analytics: UA-118569685-1

url: https://mmoanis.github.io
baseurl: /
email: mohamed_moanis@outlook.com
github: mmoanis
linkedin: mmoanis
stackoverflow: users/5504460/mohamed-moanis
skype: mohamed-moanis
steam: mmoanis
avatar: mmoanis.jpg
quora: Mohamed-Moanis
facebook: mohamed.moanis.3

#exclude: [vendor]
